#!/bin/bash
# Manual test script for Connectors Tauri guard fix
# Tests both browser preview and Tauri modes

set -e

echo "=== OpenStaff Desktop - Connectors Tauri Guard Test ==="
echo ""
echo "Testing fix for: Cannot read properties of undefined (reading 'invoke')"
echo "Commit: 75cbd9e25552fc136fb04fca1af26c30e9658bfa"
echo ""

cd "$(dirname "$0")/../apps/desktop"

echo "✓ TypeScript check..."
pnpm typecheck

echo "✓ ESLint check..."
pnpm lint

echo ""
echo "=== Test Matrix ==="
echo ""
echo "1. Browser Preview (http://localhost:5173)"
echo "   Expected: Save/Clear buttons DISABLED with tooltip"
echo "   Expected: Warning banner shown"
echo "   Expected: Test Connection works (fetch to :3000)"
echo "   Test: Click Save → Should NOT crash"
echo ""
echo "   Run: cd apps/desktop && pnpm dev"
echo "   Then open: http://localhost:5173"
echo "   Navigate to: Connectors tab"
echo "   Fill API key and click Save"
echo "   Result: No crash, button disabled message"
echo ""
echo "2. Tauri Mode (pnpm tauri:dev)"
echo "   Expected: Save/Clear buttons ENABLED"
echo "   Expected: No warning banner"
echo "   Expected: Save uses invoke → secure storage"
echo "   Test: Click Save → Key saved to Tauri secure storage"
echo ""
echo "   Run: cd apps/desktop && pnpm tauri:dev"
echo "   Navigate to: Connectors tab"
echo "   Fill API key and click Save"
echo "   Result: Key saved successfully to secure storage"
echo ""
echo "=== Implementation Details ==="
echo ""
echo "Files changed:"
echo "  - apps/desktop/src/utils/tauri.ts (NEW)"
echo "  - apps/desktop/src/utils/tauri.test.ts (NEW)"
echo "  - apps/desktop/src/components/Connectors.tsx (MODIFIED)"
echo "  - apps/desktop/src/components/stages/ChatStage.tsx (MODIFIED)"
echo ""
echo "Key changes:"
echo "  1. isTauriEnvironment() checks window.__TAURI__"
echo "  2. safeInvoke() wrapper with clear error messages"
echo "  3. getProviderKey(), saveProviderKey(), deleteProviderKey() helpers"
echo "  4. Connectors: Save/Clear buttons disabled when !isTauri"
echo "  5. Connectors: Warning banner in browser mode"
echo "  6. ChatStage: Safe key loading with getProviderKey()"
echo ""
echo "Security:"
echo "  ✓ Keys still in Tauri secure storage only"
echo "  ✓ Never localStorage or git"
echo "  ✓ No API keys in test fixtures or code"
echo ""
echo "=== All checks passed! ==="
